//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace GAT.GATAC.IntegrationService.DTOs.MobileService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationProfile", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.DTOs.MobileS" +
        "ervice")]
    public partial class OrganizationProfile : object
    {
        
        private GAT.GATAC.IntegrationService.DTOs.Picture LogoField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GAT.GATAC.IntegrationService.DTOs.Picture Logo
        {
            get
            {
                return this.LogoField;
            }
            set
            {
                this.LogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reason", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.DTOs.MobileS" +
        "ervice")]
    public partial class Reason : object
    {
        
        private System.Nullable<int> CodeInField;
        
        private System.Nullable<int> CodeOutField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodeIn
        {
            get
            {
                return this.CodeInField;
            }
            set
            {
                this.CodeInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodeOut
        {
            get
            {
                return this.CodeOutField;
            }
            set
            {
                this.CodeOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.DTOs.MobileS" +
        "ervice")]
    public partial class UserProfile : object
    {
        
        private string EmailField;
        
        private string FullNameField;
        
        private GAT.GATAC.IntegrationService.DTOs.Picture PictureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GAT.GATAC.IntegrationService.DTOs.Picture Picture
        {
            get
            {
                return this.PictureField;
            }
            set
            {
                this.PictureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.DTOs.MobileS" +
        "ervice")]
    public partial class Location : object
    {
        
        private string DescriptionField;
        
        private string MapLocationField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MapLocation
        {
            get
            {
                return this.MapLocationField;
            }
            set
            {
                this.MapLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DailyRecord", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.DTOs.MobileS" +
        "ervice")]
    public partial class DailyRecord : object
    {
        
        private System.DateTime DateField;
        
        private bool IsAbsentField;
        
        private bool IsHolidayField;
        
        private bool IsLeaveField;
        
        private bool IsWeekendField;
        
        private GAT.GATAC.IntegrationService.DTOs.MobileService.ShiftRecord[] ShiftRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAbsent
        {
            get
            {
                return this.IsAbsentField;
            }
            set
            {
                this.IsAbsentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHoliday
        {
            get
            {
                return this.IsHolidayField;
            }
            set
            {
                this.IsHolidayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLeave
        {
            get
            {
                return this.IsLeaveField;
            }
            set
            {
                this.IsLeaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWeekend
        {
            get
            {
                return this.IsWeekendField;
            }
            set
            {
                this.IsWeekendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GAT.GATAC.IntegrationService.DTOs.MobileService.ShiftRecord[] ShiftRecords
        {
            get
            {
                return this.ShiftRecordsField;
            }
            set
            {
                this.ShiftRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShiftRecord", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.DTOs.MobileS" +
        "ervice")]
    public partial class ShiftRecord : object
    {
        
        private System.Nullable<System.TimeSpan> TimeInField;
        
        private System.Nullable<System.TimeSpan> TimeOutField;
        
        private System.Nullable<System.TimeSpan> TotalHoursField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TimeIn
        {
            get
            {
                return this.TimeInField;
            }
            set
            {
                this.TimeInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TimeOut
        {
            get
            {
                return this.TimeOutField;
            }
            set
            {
                this.TimeOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> TotalHours
        {
            get
            {
                return this.TotalHoursField;
            }
            set
            {
                this.TotalHoursField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.DTOs.MobileS" +
        "ervice")]
    public partial class Booking : object
    {
        
        private System.DateTime DateTimeField;
        
        private GAT.GATAC.IntegrationService.DTOs.MobileService.Direction DirectionField;
        
        private string LocationField;
        
        private System.Nullable<int> ReasonCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GAT.GATAC.IntegrationService.DTOs.MobileService.Direction Direction
        {
            get
            {
                return this.DirectionField;
            }
            set
            {
                this.DirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Direction", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.DTOs.MobileS" +
        "ervice")]
    public enum Direction : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        In = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Out = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reason = 2,
    }
}
namespace GAT.GATAC.IntegrationService.DTOs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Picture", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.DTOs")]
    public partial class Picture : object
    {
        
        private string SrcField;
        
        private GAT.GATAC.IntegrationService.DTOs.Picture.Types TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Src
        {
            get
            {
                return this.SrcField;
            }
            set
            {
                this.SrcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GAT.GATAC.IntegrationService.DTOs.Picture.Types Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Picture.Types", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.DTOs")]
        public enum Types : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PNG = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            JPG = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            JPEG = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            BMP = 3,
        }
    }
}
namespace GAT.GATAC.IntegrationService.Exceptions
{
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public partial class LogInFailedException : System.Exception
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public partial class TokenExpiredException : System.Exception
    {
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMobileService")]
public interface IMobileService
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMobileService/GetOrganizationProfile", ReplyAction="http://tempuri.org/IMobileService/GetOrganizationProfileResponse")]
    System.IAsyncResult BeginGetOrganizationProfile(System.AsyncCallback callback, object asyncState);
    
    GAT.GATAC.IntegrationService.DTOs.MobileService.OrganizationProfile EndGetOrganizationProfile(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMobileService/GetReasons", ReplyAction="http://tempuri.org/IMobileService/GetReasonsResponse")]
    System.IAsyncResult BeginGetReasons(System.AsyncCallback callback, object asyncState);
    
    GAT.GATAC.IntegrationService.DTOs.MobileService.Reason[] EndGetReasons(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMobileService/GetMobileToken", ReplyAction="http://tempuri.org/IMobileService/GetMobileTokenResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GAT.GATAC.IntegrationService.Exceptions.LogInFailedException), Action="http://tempuri.org/IMobileService/GetMobileTokenLogInFailedExceptionFault", Name="LogInFailedException", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.Exceptions")]
    System.IAsyncResult BeginGetMobileToken(string userName, string password, System.AsyncCallback callback, object asyncState);
    
    System.Guid EndGetMobileToken(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMobileService/GetUserProfile", ReplyAction="http://tempuri.org/IMobileService/GetUserProfileResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GAT.GATAC.IntegrationService.Exceptions.TokenExpiredException), Action="http://tempuri.org/IMobileService/GetUserProfileTokenExpiredExceptionFault", Name="TokenExpiredException", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.Exceptions")]
    System.IAsyncResult BeginGetUserProfile(System.Guid mobileToken, System.AsyncCallback callback, object asyncState);
    
    GAT.GATAC.IntegrationService.DTOs.MobileService.UserProfile EndGetUserProfile(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMobileService/GetAssignedLocations", ReplyAction="http://tempuri.org/IMobileService/GetAssignedLocationsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GAT.GATAC.IntegrationService.Exceptions.TokenExpiredException), Action="http://tempuri.org/IMobileService/GetAssignedLocationsTokenExpiredExceptionFault", Name="TokenExpiredException", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.Exceptions")]
    System.IAsyncResult BeginGetAssignedLocations(System.Guid mobileToken, System.AsyncCallback callback, object asyncState);
    
    GAT.GATAC.IntegrationService.DTOs.MobileService.Location[] EndGetAssignedLocations(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMobileService/GetAttendance", ReplyAction="http://tempuri.org/IMobileService/GetAttendanceResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GAT.GATAC.IntegrationService.Exceptions.TokenExpiredException), Action="http://tempuri.org/IMobileService/GetAttendanceTokenExpiredExceptionFault", Name="TokenExpiredException", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.Exceptions")]
    System.IAsyncResult BeginGetAttendance(System.Guid mobileToken, System.DateTime fromDate, System.DateTime toDate, System.AsyncCallback callback, object asyncState);
    
    GAT.GATAC.IntegrationService.DTOs.MobileService.DailyRecord[] EndGetAttendance(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMobileService/UploadBookings", ReplyAction="http://tempuri.org/IMobileService/UploadBookingsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GAT.GATAC.IntegrationService.Exceptions.TokenExpiredException), Action="http://tempuri.org/IMobileService/UploadBookingsTokenExpiredExceptionFault", Name="TokenExpiredException", Namespace="http://schemas.datacontract.org/2004/07/GAT.GATAC.IntegrationService.Exceptions")]
    System.IAsyncResult BeginUploadBookings(System.Guid mobileToken, GAT.GATAC.IntegrationService.DTOs.MobileService.Booking[] bookings, System.AsyncCallback callback, object asyncState);
    
    void EndUploadBookings(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMobileServiceChannel : IMobileService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetOrganizationProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetOrganizationProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public GAT.GATAC.IntegrationService.DTOs.MobileService.OrganizationProfile Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((GAT.GATAC.IntegrationService.DTOs.MobileService.OrganizationProfile)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetReasonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetReasonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public GAT.GATAC.IntegrationService.DTOs.MobileService.Reason[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((GAT.GATAC.IntegrationService.DTOs.MobileService.Reason[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetMobileTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetMobileTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public System.Guid Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((System.Guid)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetUserProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetUserProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public GAT.GATAC.IntegrationService.DTOs.MobileService.UserProfile Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((GAT.GATAC.IntegrationService.DTOs.MobileService.UserProfile)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetAssignedLocationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetAssignedLocationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public GAT.GATAC.IntegrationService.DTOs.MobileService.Location[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((GAT.GATAC.IntegrationService.DTOs.MobileService.Location[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetAttendanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetAttendanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public GAT.GATAC.IntegrationService.DTOs.MobileService.DailyRecord[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((GAT.GATAC.IntegrationService.DTOs.MobileService.DailyRecord[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MobileServiceClient : System.ServiceModel.ClientBase<IMobileService>, IMobileService
{
    
    private BeginOperationDelegate onBeginGetOrganizationProfileDelegate;
    
    private EndOperationDelegate onEndGetOrganizationProfileDelegate;
    
    private System.Threading.SendOrPostCallback onGetOrganizationProfileCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetReasonsDelegate;
    
    private EndOperationDelegate onEndGetReasonsDelegate;
    
    private System.Threading.SendOrPostCallback onGetReasonsCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetMobileTokenDelegate;
    
    private EndOperationDelegate onEndGetMobileTokenDelegate;
    
    private System.Threading.SendOrPostCallback onGetMobileTokenCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetUserProfileDelegate;
    
    private EndOperationDelegate onEndGetUserProfileDelegate;
    
    private System.Threading.SendOrPostCallback onGetUserProfileCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetAssignedLocationsDelegate;
    
    private EndOperationDelegate onEndGetAssignedLocationsDelegate;
    
    private System.Threading.SendOrPostCallback onGetAssignedLocationsCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetAttendanceDelegate;
    
    private EndOperationDelegate onEndGetAttendanceDelegate;
    
    private System.Threading.SendOrPostCallback onGetAttendanceCompletedDelegate;
    
    private BeginOperationDelegate onBeginUploadBookingsDelegate;
    
    private EndOperationDelegate onEndUploadBookingsDelegate;
    
    private System.Threading.SendOrPostCallback onUploadBookingsCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public MobileServiceClient()
    {
    }
    
    public MobileServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MobileServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MobileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MobileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<GetOrganizationProfileCompletedEventArgs> GetOrganizationProfileCompleted;
    
    public event System.EventHandler<GetReasonsCompletedEventArgs> GetReasonsCompleted;
    
    public event System.EventHandler<GetMobileTokenCompletedEventArgs> GetMobileTokenCompleted;
    
    public event System.EventHandler<GetUserProfileCompletedEventArgs> GetUserProfileCompleted;
    
    public event System.EventHandler<GetAssignedLocationsCompletedEventArgs> GetAssignedLocationsCompleted;
    
    public event System.EventHandler<GetAttendanceCompletedEventArgs> GetAttendanceCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UploadBookingsCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMobileService.BeginGetOrganizationProfile(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetOrganizationProfile(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GAT.GATAC.IntegrationService.DTOs.MobileService.OrganizationProfile IMobileService.EndGetOrganizationProfile(System.IAsyncResult result)
    {
        return base.Channel.EndGetOrganizationProfile(result);
    }
    
    private System.IAsyncResult OnBeginGetOrganizationProfile(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IMobileService)(this)).BeginGetOrganizationProfile(callback, asyncState);
    }
    
    private object[] OnEndGetOrganizationProfile(System.IAsyncResult result)
    {
        GAT.GATAC.IntegrationService.DTOs.MobileService.OrganizationProfile retVal = ((IMobileService)(this)).EndGetOrganizationProfile(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetOrganizationProfileCompleted(object state)
    {
        if ((this.GetOrganizationProfileCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetOrganizationProfileCompleted(this, new GetOrganizationProfileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetOrganizationProfileAsync()
    {
        this.GetOrganizationProfileAsync(null);
    }
    
    public void GetOrganizationProfileAsync(object userState)
    {
        if ((this.onBeginGetOrganizationProfileDelegate == null))
        {
            this.onBeginGetOrganizationProfileDelegate = new BeginOperationDelegate(this.OnBeginGetOrganizationProfile);
        }
        if ((this.onEndGetOrganizationProfileDelegate == null))
        {
            this.onEndGetOrganizationProfileDelegate = new EndOperationDelegate(this.OnEndGetOrganizationProfile);
        }
        if ((this.onGetOrganizationProfileCompletedDelegate == null))
        {
            this.onGetOrganizationProfileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrganizationProfileCompleted);
        }
        base.InvokeAsync(this.onBeginGetOrganizationProfileDelegate, null, this.onEndGetOrganizationProfileDelegate, this.onGetOrganizationProfileCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMobileService.BeginGetReasons(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetReasons(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GAT.GATAC.IntegrationService.DTOs.MobileService.Reason[] IMobileService.EndGetReasons(System.IAsyncResult result)
    {
        return base.Channel.EndGetReasons(result);
    }
    
    private System.IAsyncResult OnBeginGetReasons(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IMobileService)(this)).BeginGetReasons(callback, asyncState);
    }
    
    private object[] OnEndGetReasons(System.IAsyncResult result)
    {
        GAT.GATAC.IntegrationService.DTOs.MobileService.Reason[] retVal = ((IMobileService)(this)).EndGetReasons(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetReasonsCompleted(object state)
    {
        if ((this.GetReasonsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetReasonsCompleted(this, new GetReasonsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetReasonsAsync()
    {
        this.GetReasonsAsync(null);
    }
    
    public void GetReasonsAsync(object userState)
    {
        if ((this.onBeginGetReasonsDelegate == null))
        {
            this.onBeginGetReasonsDelegate = new BeginOperationDelegate(this.OnBeginGetReasons);
        }
        if ((this.onEndGetReasonsDelegate == null))
        {
            this.onEndGetReasonsDelegate = new EndOperationDelegate(this.OnEndGetReasons);
        }
        if ((this.onGetReasonsCompletedDelegate == null))
        {
            this.onGetReasonsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetReasonsCompleted);
        }
        base.InvokeAsync(this.onBeginGetReasonsDelegate, null, this.onEndGetReasonsDelegate, this.onGetReasonsCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMobileService.BeginGetMobileToken(string userName, string password, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetMobileToken(userName, password, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Guid IMobileService.EndGetMobileToken(System.IAsyncResult result)
    {
        return base.Channel.EndGetMobileToken(result);
    }
    
    private System.IAsyncResult OnBeginGetMobileToken(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string userName = ((string)(inValues[0]));
        string password = ((string)(inValues[1]));
        return ((IMobileService)(this)).BeginGetMobileToken(userName, password, callback, asyncState);
    }
    
    private object[] OnEndGetMobileToken(System.IAsyncResult result)
    {
        System.Guid retVal = ((IMobileService)(this)).EndGetMobileToken(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetMobileTokenCompleted(object state)
    {
        if ((this.GetMobileTokenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetMobileTokenCompleted(this, new GetMobileTokenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetMobileTokenAsync(string userName, string password)
    {
        this.GetMobileTokenAsync(userName, password, null);
    }
    
    public void GetMobileTokenAsync(string userName, string password, object userState)
    {
        if ((this.onBeginGetMobileTokenDelegate == null))
        {
            this.onBeginGetMobileTokenDelegate = new BeginOperationDelegate(this.OnBeginGetMobileToken);
        }
        if ((this.onEndGetMobileTokenDelegate == null))
        {
            this.onEndGetMobileTokenDelegate = new EndOperationDelegate(this.OnEndGetMobileToken);
        }
        if ((this.onGetMobileTokenCompletedDelegate == null))
        {
            this.onGetMobileTokenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMobileTokenCompleted);
        }
        base.InvokeAsync(this.onBeginGetMobileTokenDelegate, new object[] {
                    userName,
                    password}, this.onEndGetMobileTokenDelegate, this.onGetMobileTokenCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMobileService.BeginGetUserProfile(System.Guid mobileToken, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetUserProfile(mobileToken, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GAT.GATAC.IntegrationService.DTOs.MobileService.UserProfile IMobileService.EndGetUserProfile(System.IAsyncResult result)
    {
        return base.Channel.EndGetUserProfile(result);
    }
    
    private System.IAsyncResult OnBeginGetUserProfile(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid mobileToken = ((System.Guid)(inValues[0]));
        return ((IMobileService)(this)).BeginGetUserProfile(mobileToken, callback, asyncState);
    }
    
    private object[] OnEndGetUserProfile(System.IAsyncResult result)
    {
        GAT.GATAC.IntegrationService.DTOs.MobileService.UserProfile retVal = ((IMobileService)(this)).EndGetUserProfile(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetUserProfileCompleted(object state)
    {
        if ((this.GetUserProfileCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetUserProfileCompleted(this, new GetUserProfileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetUserProfileAsync(System.Guid mobileToken)
    {
        this.GetUserProfileAsync(mobileToken, null);
    }
    
    public void GetUserProfileAsync(System.Guid mobileToken, object userState)
    {
        if ((this.onBeginGetUserProfileDelegate == null))
        {
            this.onBeginGetUserProfileDelegate = new BeginOperationDelegate(this.OnBeginGetUserProfile);
        }
        if ((this.onEndGetUserProfileDelegate == null))
        {
            this.onEndGetUserProfileDelegate = new EndOperationDelegate(this.OnEndGetUserProfile);
        }
        if ((this.onGetUserProfileCompletedDelegate == null))
        {
            this.onGetUserProfileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserProfileCompleted);
        }
        base.InvokeAsync(this.onBeginGetUserProfileDelegate, new object[] {
                    mobileToken}, this.onEndGetUserProfileDelegate, this.onGetUserProfileCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMobileService.BeginGetAssignedLocations(System.Guid mobileToken, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetAssignedLocations(mobileToken, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GAT.GATAC.IntegrationService.DTOs.MobileService.Location[] IMobileService.EndGetAssignedLocations(System.IAsyncResult result)
    {
        return base.Channel.EndGetAssignedLocations(result);
    }
    
    private System.IAsyncResult OnBeginGetAssignedLocations(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid mobileToken = ((System.Guid)(inValues[0]));
        return ((IMobileService)(this)).BeginGetAssignedLocations(mobileToken, callback, asyncState);
    }
    
    private object[] OnEndGetAssignedLocations(System.IAsyncResult result)
    {
        GAT.GATAC.IntegrationService.DTOs.MobileService.Location[] retVal = ((IMobileService)(this)).EndGetAssignedLocations(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetAssignedLocationsCompleted(object state)
    {
        if ((this.GetAssignedLocationsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetAssignedLocationsCompleted(this, new GetAssignedLocationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetAssignedLocationsAsync(System.Guid mobileToken)
    {
        this.GetAssignedLocationsAsync(mobileToken, null);
    }
    
    public void GetAssignedLocationsAsync(System.Guid mobileToken, object userState)
    {
        if ((this.onBeginGetAssignedLocationsDelegate == null))
        {
            this.onBeginGetAssignedLocationsDelegate = new BeginOperationDelegate(this.OnBeginGetAssignedLocations);
        }
        if ((this.onEndGetAssignedLocationsDelegate == null))
        {
            this.onEndGetAssignedLocationsDelegate = new EndOperationDelegate(this.OnEndGetAssignedLocations);
        }
        if ((this.onGetAssignedLocationsCompletedDelegate == null))
        {
            this.onGetAssignedLocationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAssignedLocationsCompleted);
        }
        base.InvokeAsync(this.onBeginGetAssignedLocationsDelegate, new object[] {
                    mobileToken}, this.onEndGetAssignedLocationsDelegate, this.onGetAssignedLocationsCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMobileService.BeginGetAttendance(System.Guid mobileToken, System.DateTime fromDate, System.DateTime toDate, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetAttendance(mobileToken, fromDate, toDate, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GAT.GATAC.IntegrationService.DTOs.MobileService.DailyRecord[] IMobileService.EndGetAttendance(System.IAsyncResult result)
    {
        return base.Channel.EndGetAttendance(result);
    }
    
    private System.IAsyncResult OnBeginGetAttendance(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid mobileToken = ((System.Guid)(inValues[0]));
        System.DateTime fromDate = ((System.DateTime)(inValues[1]));
        System.DateTime toDate = ((System.DateTime)(inValues[2]));
        return ((IMobileService)(this)).BeginGetAttendance(mobileToken, fromDate, toDate, callback, asyncState);
    }
    
    private object[] OnEndGetAttendance(System.IAsyncResult result)
    {
        GAT.GATAC.IntegrationService.DTOs.MobileService.DailyRecord[] retVal = ((IMobileService)(this)).EndGetAttendance(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetAttendanceCompleted(object state)
    {
        if ((this.GetAttendanceCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetAttendanceCompleted(this, new GetAttendanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetAttendanceAsync(System.Guid mobileToken, System.DateTime fromDate, System.DateTime toDate)
    {
        this.GetAttendanceAsync(mobileToken, fromDate, toDate, null);
    }
    
    public void GetAttendanceAsync(System.Guid mobileToken, System.DateTime fromDate, System.DateTime toDate, object userState)
    {
        if ((this.onBeginGetAttendanceDelegate == null))
        {
            this.onBeginGetAttendanceDelegate = new BeginOperationDelegate(this.OnBeginGetAttendance);
        }
        if ((this.onEndGetAttendanceDelegate == null))
        {
            this.onEndGetAttendanceDelegate = new EndOperationDelegate(this.OnEndGetAttendance);
        }
        if ((this.onGetAttendanceCompletedDelegate == null))
        {
            this.onGetAttendanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAttendanceCompleted);
        }
        base.InvokeAsync(this.onBeginGetAttendanceDelegate, new object[] {
                    mobileToken,
                    fromDate,
                    toDate}, this.onEndGetAttendanceDelegate, this.onGetAttendanceCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMobileService.BeginUploadBookings(System.Guid mobileToken, GAT.GATAC.IntegrationService.DTOs.MobileService.Booking[] bookings, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUploadBookings(mobileToken, bookings, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IMobileService.EndUploadBookings(System.IAsyncResult result)
    {
        base.Channel.EndUploadBookings(result);
    }
    
    private System.IAsyncResult OnBeginUploadBookings(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Guid mobileToken = ((System.Guid)(inValues[0]));
        GAT.GATAC.IntegrationService.DTOs.MobileService.Booking[] bookings = ((GAT.GATAC.IntegrationService.DTOs.MobileService.Booking[])(inValues[1]));
        return ((IMobileService)(this)).BeginUploadBookings(mobileToken, bookings, callback, asyncState);
    }
    
    private object[] OnEndUploadBookings(System.IAsyncResult result)
    {
        ((IMobileService)(this)).EndUploadBookings(result);
        return null;
    }
    
    private void OnUploadBookingsCompleted(object state)
    {
        if ((this.UploadBookingsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.UploadBookingsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void UploadBookingsAsync(System.Guid mobileToken, GAT.GATAC.IntegrationService.DTOs.MobileService.Booking[] bookings)
    {
        this.UploadBookingsAsync(mobileToken, bookings, null);
    }
    
    public void UploadBookingsAsync(System.Guid mobileToken, GAT.GATAC.IntegrationService.DTOs.MobileService.Booking[] bookings, object userState)
    {
        if ((this.onBeginUploadBookingsDelegate == null))
        {
            this.onBeginUploadBookingsDelegate = new BeginOperationDelegate(this.OnBeginUploadBookings);
        }
        if ((this.onEndUploadBookingsDelegate == null))
        {
            this.onEndUploadBookingsDelegate = new EndOperationDelegate(this.OnEndUploadBookings);
        }
        if ((this.onUploadBookingsCompletedDelegate == null))
        {
            this.onUploadBookingsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadBookingsCompleted);
        }
        base.InvokeAsync(this.onBeginUploadBookingsDelegate, new object[] {
                    mobileToken,
                    bookings}, this.onEndUploadBookingsDelegate, this.onUploadBookingsCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IMobileService CreateChannel()
    {
        return new MobileServiceClientChannel(this);
    }
    
    private class MobileServiceClientChannel : ChannelBase<IMobileService>, IMobileService
    {
        
        public MobileServiceClientChannel(System.ServiceModel.ClientBase<IMobileService> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetOrganizationProfile(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("GetOrganizationProfile", _args, callback, asyncState);
            return _result;
        }
        
        public GAT.GATAC.IntegrationService.DTOs.MobileService.OrganizationProfile EndGetOrganizationProfile(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GAT.GATAC.IntegrationService.DTOs.MobileService.OrganizationProfile _result = ((GAT.GATAC.IntegrationService.DTOs.MobileService.OrganizationProfile)(base.EndInvoke("GetOrganizationProfile", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetReasons(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("GetReasons", _args, callback, asyncState);
            return _result;
        }
        
        public GAT.GATAC.IntegrationService.DTOs.MobileService.Reason[] EndGetReasons(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GAT.GATAC.IntegrationService.DTOs.MobileService.Reason[] _result = ((GAT.GATAC.IntegrationService.DTOs.MobileService.Reason[])(base.EndInvoke("GetReasons", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetMobileToken(string userName, string password, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = userName;
            _args[1] = password;
            System.IAsyncResult _result = base.BeginInvoke("GetMobileToken", _args, callback, asyncState);
            return _result;
        }
        
        public System.Guid EndGetMobileToken(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            System.Guid _result = ((System.Guid)(base.EndInvoke("GetMobileToken", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetUserProfile(System.Guid mobileToken, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = mobileToken;
            System.IAsyncResult _result = base.BeginInvoke("GetUserProfile", _args, callback, asyncState);
            return _result;
        }
        
        public GAT.GATAC.IntegrationService.DTOs.MobileService.UserProfile EndGetUserProfile(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GAT.GATAC.IntegrationService.DTOs.MobileService.UserProfile _result = ((GAT.GATAC.IntegrationService.DTOs.MobileService.UserProfile)(base.EndInvoke("GetUserProfile", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetAssignedLocations(System.Guid mobileToken, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = mobileToken;
            System.IAsyncResult _result = base.BeginInvoke("GetAssignedLocations", _args, callback, asyncState);
            return _result;
        }
        
        public GAT.GATAC.IntegrationService.DTOs.MobileService.Location[] EndGetAssignedLocations(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GAT.GATAC.IntegrationService.DTOs.MobileService.Location[] _result = ((GAT.GATAC.IntegrationService.DTOs.MobileService.Location[])(base.EndInvoke("GetAssignedLocations", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetAttendance(System.Guid mobileToken, System.DateTime fromDate, System.DateTime toDate, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = mobileToken;
            _args[1] = fromDate;
            _args[2] = toDate;
            System.IAsyncResult _result = base.BeginInvoke("GetAttendance", _args, callback, asyncState);
            return _result;
        }
        
        public GAT.GATAC.IntegrationService.DTOs.MobileService.DailyRecord[] EndGetAttendance(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GAT.GATAC.IntegrationService.DTOs.MobileService.DailyRecord[] _result = ((GAT.GATAC.IntegrationService.DTOs.MobileService.DailyRecord[])(base.EndInvoke("GetAttendance", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginUploadBookings(System.Guid mobileToken, GAT.GATAC.IntegrationService.DTOs.MobileService.Booking[] bookings, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = mobileToken;
            _args[1] = bookings;
            System.IAsyncResult _result = base.BeginInvoke("UploadBookings", _args, callback, asyncState);
            return _result;
        }
        
        public void EndUploadBookings(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("UploadBookings", _args, result);
        }
    }
}
