//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GantnerMe.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GantnerMe.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you need to.
        /// </summary>
        internal static string areyousureyouneedto {
            get {
                return ResourceManager.GetString("areyousureyouneedto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in / Check out.
        /// </summary>
        internal static string CheckInCheckout {
            get {
                return ResourceManager.GetString("CheckInCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIN/OUT.
        /// </summary>
        internal static string checkinout {
            get {
                return ResourceManager.GetString("checkinout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection!.
        /// </summary>
        internal static string checkyourinternetconnection {
            get {
                return ResourceManager.GetString("checkyourinternetconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming (Check IN).
        /// </summary>
        internal static string comingcheckin {
            get {
                return ResourceManager.GetString("comingcheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string configurations {
            get {
                return ResourceManager.GetString("configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration URL.
        /// </summary>
        internal static string configurl {
            get {
                return ResourceManager.GetString("configurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Url updated successfully!.
        /// </summary>
        internal static string Configurlupdated {
            get {
                return ResourceManager.GetString("Configurlupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Configurations.
        /// </summary>
        internal static string editconfigurations {
            get {
                return ResourceManager.GetString("editconfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Login Credentials.
        /// </summary>
        internal static string enterlogincredentials {
            get {
                return ResourceManager.GetString("enterlogincredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password!.
        /// </summary>
        internal static string enterpassword {
            get {
                return ResourceManager.GetString("enterpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter server link.
        /// </summary>
        internal static string EnterServerLink {
            get {
                return ResourceManager.GetString("EnterServerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username!.
        /// </summary>
        internal static string enterusername {
            get {
                return ResourceManager.GetString("enterusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to server.
        /// </summary>
        internal static string failedtoconnecttoserver {
            get {
                return ResourceManager.GetString("failedtoconnecttoserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How was your Day?.
        /// </summary>
        internal static string howwasyourday {
            get {
                return ResourceManager.GetString("howwasyourday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language updated successfully!.
        /// </summary>
        internal static string LanguageUpdated {
            get {
                return ResourceManager.GetString("LanguageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving (Check Out).
        /// </summary>
        internal static string leavingcheckout {
            get {
                return ResourceManager.GetString("leavingcheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        internal static string Loginfailed {
            get {
                return ResourceManager.GetString("Loginfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Attendence.
        /// </summary>
        internal static string myattendence {
            get {
                return ResourceManager.GetString("myattendence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a function.
        /// </summary>
        internal static string pleasechoseafunction {
            get {
                return ResourceManager.GetString("pleasechoseafunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter server link!.
        /// </summary>
        internal static string pleaseenterserverlink {
            get {
                return ResourceManager.GetString("pleaseenterserverlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid url format!.
        /// </summary>
        internal static string pleaseentervalidserverlink {
            get {
                return ResourceManager.GetString("pleaseentervalidserverlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons.
        /// </summary>
        internal static string reasons {
            get {
                return ResourceManager.GetString("reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated!.
        /// </summary>
        internal static string recordupdated {
            get {
                return ResourceManager.GetString("recordupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been saved successfully!.
        /// </summary>
        internal static string ReuqestSaved {
            get {
                return ResourceManager.GetString("ReuqestSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a option.
        /// </summary>
        internal static string selectoption {
            get {
                return ResourceManager.GetString("selectoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Language.
        /// </summary>
        internal static string selectyourlanguage {
            get {
                return ResourceManager.GetString("selectyourlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send your current location as.
        /// </summary>
        internal static string sendyourcurentlocation {
            get {
                return ResourceManager.GetString("sendyourcurentlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction location.
        /// </summary>
        internal static string transactionlocation {
            get {
                return ResourceManager.GetString("transactionlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
